####MODS HERE
mods = [""]

####YOU HAVE TO REPLACE THIS WITH ANY OTHER EXTREMELY HIGHLY TRUSTED PEOPLE.
superTrusted = [""]

####HIGHLY RECCOMMENDED ONLY BROADCASTERS GO IN HERE
broadcaster = ""